#!/usr/bin/env python3
"""Generate the iOS distro icon catalog from apps/desktop/src/hosts/distroIcons.ts.

Writes one SVG image set per icon into Assets.xcassets/Distro (template
rendering, vector data preserved) plus DistroIcons.swift with the id / title /
brand colour table. Run after editing the desktop catalog:

    python3 apps/ios/scripts/gen-distro-icons.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "apps/desktop/src/hosts/distroIcons.ts"
ASSETS = ROOT / "apps/ios/Termoso/Resources/Assets.xcassets/Distro"
SWIFT = ROOT / "apps/ios/Termoso/UI/Components/DistroIcons.swift"

ENTRY = re.compile(
    r'id:\s*"(?P<id>[^"]+)",\s*title:\s*"(?P<title>[^"]+)",\s*color:\s*"(?P<color>#[0-9A-Fa-f]{6})",\s*path:\s*"(?P<path>[^"]+)"',
    re.S,
)
ALIASES = re.compile(r"^\s*(?P<alias>[a-z0-9]+):\s*\"(?P<id>[a-z0-9]+)\",\s*$", re.M)


NUMBER = re.compile(r"[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?")


def normalize(path: str) -> str:
    """Expand minified arc arguments (`a3 3 0 01-.9.5` → `a3 3 0 0 1 -.9 .5`).

    Simple Icons pack the two arc flags into one token, which lenient
    browser parsers accept but stricter ones (and the Compose parser) do not.
    Every command is re-emitted with space-separated arguments.
    """
    out: list[str] = []
    i = 0
    n = len(path)
    cmd = ""
    while i < n:
        ch = path[i]
        if ch.isalpha():
            cmd = ch
            out.append(ch)
            i += 1
            continue
        if ch in " ,\t\n\r":
            i += 1
            continue
        if cmd in "aA":
            args: list[str] = []
            while len(args) < 7 and i < n:
                while i < n and path[i] in " ,\t\n\r":
                    i += 1
                if len(args) in (3, 4):
                    if i < n and path[i] in "01":
                        args.append(path[i])
                        i += 1
                        continue
                    raise ValueError(f"bad arc flag at {i} in {path[:40]}…")
                m = NUMBER.match(path, i)
                if not m:
                    raise ValueError(f"bad arc number at {i} in {path[:40]}…")
                args.append(m.group(0))
                i = m.end()
            out.append(" ".join(args))
            continue
        m = NUMBER.match(path, i)
        if not m:
            raise ValueError(f"unexpected {ch!r} at {i} in {path[:40]}…")
        out.append(m.group(0))
        i = m.end()
    return " ".join(out).replace("  ", " ")


def main() -> int:
    text = SOURCE.read_text()
    icons = [m.groupdict() for m in ENTRY.finditer(text)]
    if not icons:
        print("no icons parsed", file=sys.stderr)
        return 1
    ids = {i["id"] for i in icons}

    aliases: dict[str, str] = {}
    alias_block = re.search(r"const aliases[^{]*\{(.*?)\n\};", text, re.S)
    if alias_block:
        for m in ALIASES.finditer(alias_block.group(1)):
            if m.group("id") in ids:
                aliases[m.group("alias")] = m.group("id")

    ASSETS.mkdir(parents=True, exist_ok=True)
    (ASSETS / "Contents.json").write_text(
        json.dumps({"info": {"author": "xcode", "version": 1}, "properties": {"provides-namespace": True}}, indent=2) + "\n"
    )
    for icon in icons:
        folder = ASSETS / f"{icon['id']}.imageset"
        folder.mkdir(exist_ok=True)
        svg = (
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">'
            f'<path fill="#000" d="{normalize(icon["path"])}"/></svg>\n'
        )
        (folder / f"{icon['id']}.svg").write_text(svg)
        (folder / "Contents.json").write_text(
            json.dumps(
                {
                    "images": [{"filename": f"{icon['id']}.svg", "idiom": "universal"}],
                    "info": {"author": "xcode", "version": 1},
                    "properties": {"preserves-vector-representation": True, "template-rendering-intent": "template"},
                },
                indent=2,
            )
            + "\n"
        )

    lines = [
        "// Generated by apps/ios/scripts/gen-distro-icons.py from",
        "// apps/desktop/src/hosts/distroIcons.ts — do not edit by hand.",
        "// Glyphs: Simple Icons (CC0-1.0) except windows (Devicon, MIT), mageia",
        "// (Font Logos, Unlicense) and amazon (Material Icons, Apache-2.0).",
        "",
        "import SwiftUI",
        "",
        "struct DistroIcon: Identifiable, Hashable {",
        "    let id: String",
        "    let title: String",
        "    let color: Color",
        "",
        "    /// Template image from the `Distro` asset namespace.",
        "    var image: Image { Image(\"Distro/\\(id)\") }",
        "}",
        "",
        "enum DistroIcons {",
        "    static let all: [DistroIcon] = [",
    ]
    for icon in icons:
        c = icon["color"].lstrip("#")
        lines.append(
            f'        DistroIcon(id: "{icon["id"]}", title: "{icon["title"]}", color: Color(red: 0x{c[0:2]} / 255.0, green: 0x{c[2:4]} / 255.0, blue: 0x{c[4:6]} / 255.0)),'
        )
    lines += [
        "    ]",
        "",
        "    private static let byId: [String: DistroIcon] = Dictionary(uniqueKeysWithValues: all.map { ($0.id, $0) })",
        "",
        "    private static let aliases: [String: String] = [",
    ]
    for alias, target in sorted(aliases.items()):
        lines.append(f'        "{alias}": "{target}",')
    lines += [
        "    ]",
        "",
        "    /// Icon for a stored `osName`; tolerates legacy free-form values (\"Ubuntu 22.04\").",
        "    static func forOs(_ osName: String?) -> DistroIcon? {",
        "        let key = (osName ?? \"\").trimmingCharacters(in: .whitespacesAndNewlines).lowercased()",
        "        if key.isEmpty { return nil }",
        "        if let icon = byId[aliases[key] ?? key] { return icon }",
        "        if let icon = all.first(where: { $0.id != \"linux\" && key.contains($0.id) }) { return icon }",
        "        return key.contains(\"linux\") ? byId[\"linux\"] : nil",
        "    }",
        "}",
        "",
    ]
    SWIFT.parent.mkdir(parents=True, exist_ok=True)
    SWIFT.write_text("\n".join(lines))
    print(f"{len(icons)} icons, {len(aliases)} aliases → {ASSETS.relative_to(ROOT)}, {SWIFT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
