import type { ITheme } from "@xterm/xterm";
import { dark, emerald, light } from "@/theme/theme";

/** Emerald-accented terminal palettes matching the app color schemes. */
export const terminalThemes: Record<"dark" | "light", ITheme> = {
  dark: {
    background: dark.bg,
    foreground: dark.text,
    cursor: emerald.main,
    cursorAccent: dark.bg,
    selectionBackground: "rgba(43, 184, 132, 0.32)",
    selectionInactiveBackground: "rgba(43, 184, 132, 0.18)",
    black: "#1A1E2B",
    red: "#F25E61",
    green: "#2BB884",
    yellow: "#F2C94C",
    blue: "#5AA9E6",
    magenta: "#C58AF9",
    cyan: "#4FD1C5",
    white: "#C9CDDA",
    brightBlack: "#5A6076",
    brightRed: "#FF8285",
    brightGreen: "#5FD0A4",
    brightYellow: "#FFDB7A",
    brightBlue: "#8CC5F0",
    brightMagenta: "#DBB3FF",
    brightCyan: "#84E7DD",
    brightWhite: "#F2F4FA",
  },
  light: {
    background: light.surface,
    foreground: light.text,
    cursor: emerald.dark,
    cursorAccent: light.surface,
    selectionBackground: "rgba(31, 143, 102, 0.28)",
    selectionInactiveBackground: "rgba(31, 143, 102, 0.16)",
    black: "#171B26",
    red: "#C93B3E",
    green: "#1F8F66",
    yellow: "#B08A12",
    blue: "#2C6B9C",
    magenta: "#8A4FCF",
    cyan: "#1C8C82",
    white: "#9AA3B2",
    brightBlack: "#5F6B7C",
    brightRed: "#F25E61",
    brightGreen: "#2BB884",
    brightYellow: "#D6A81C",
    brightBlue: "#3D86BF",
    brightMagenta: "#A66BE8",
    brightCyan: "#28A89C",
    brightWhite: "#CBD2DC",
  },
};
