// Generated by apps/ios/scripts/gen-distro-icons.py from
// apps/desktop/src/hosts/distroIcons.ts — do not edit by hand.
// Glyphs: Simple Icons (CC0-1.0) except windows (Devicon, MIT), mageia
// (Font Logos, Unlicense) and amazon (Material Icons, Apache-2.0).

import SwiftUI

struct DistroIcon: Identifiable, Hashable {
    let id: String
    let title: String
    let color: Color

    /// Template image from the `Distro` asset namespace.
    var image: Image { Image("Distro/\(id)") }
}

enum DistroIcons {
    static let all: [DistroIcon] = [
        DistroIcon(id: "ubuntu", title: "Ubuntu", color: Color(red: 0xE9 / 255.0, green: 0x54 / 255.0, blue: 0x20 / 255.0)),
        DistroIcon(id: "debian", title: "Debian", color: Color(red: 0xA8 / 255.0, green: 0x1D / 255.0, blue: 0x33 / 255.0)),
        DistroIcon(id: "raspbian", title: "Raspberry Pi OS", color: Color(red: 0xA2 / 255.0, green: 0x28 / 255.0, blue: 0x46 / 255.0)),
        DistroIcon(id: "fedora", title: "Fedora", color: Color(red: 0x3C / 255.0, green: 0x8F / 255.0, blue: 0xD0 / 255.0)),
        DistroIcon(id: "redhat", title: "Red Hat Enterprise Linux", color: Color(red: 0xD6 / 255.0, green: 0x2B / 255.0, blue: 0x2B / 255.0)),
        DistroIcon(id: "centos", title: "CentOS", color: Color(red: 0x93 / 255.0, green: 0x22 / 255.0, blue: 0x79 / 255.0)),
        DistroIcon(id: "rocky", title: "Rocky Linux", color: Color(red: 0x10 / 255.0, green: 0xB9 / 255.0, blue: 0x81 / 255.0)),
        DistroIcon(id: "alma", title: "AlmaLinux", color: Color(red: 0x2A / 255.0, green: 0x6F / 255.0, blue: 0xBF / 255.0)),
        DistroIcon(id: "suse", title: "openSUSE / SLES", color: Color(red: 0x73 / 255.0, green: 0xBA / 255.0, blue: 0x25 / 255.0)),
        DistroIcon(id: "arch", title: "Arch Linux", color: Color(red: 0x17 / 255.0, green: 0x93 / 255.0, blue: 0xD1 / 255.0)),
        DistroIcon(id: "manjaro", title: "Manjaro", color: Color(red: 0x2A / 255.0, green: 0xA5 / 255.0, blue: 0x8E / 255.0)),
        DistroIcon(id: "gentoo", title: "Gentoo", color: Color(red: 0x54 / 255.0, green: 0x48 / 255.0, blue: 0x7A / 255.0)),
        DistroIcon(id: "alpine", title: "Alpine Linux", color: Color(red: 0x0D / 255.0, green: 0x59 / 255.0, blue: 0x7F / 255.0)),
        DistroIcon(id: "nixos", title: "NixOS", color: Color(red: 0x52 / 255.0, green: 0x77 / 255.0, blue: 0xC3 / 255.0)),
        DistroIcon(id: "mint", title: "Linux Mint", color: Color(red: 0x6F / 255.0, green: 0xA8 / 255.0, blue: 0x34 / 255.0)),
        DistroIcon(id: "kali", title: "Kali Linux", color: Color(red: 0x55 / 255.0, green: 0x7C / 255.0, blue: 0x94 / 255.0)),
        DistroIcon(id: "linux", title: "Linux", color: Color(red: 0xC5 / 255.0, green: 0x8A / 255.0, blue: 0x12 / 255.0)),
        DistroIcon(id: "freebsd", title: "FreeBSD", color: Color(red: 0xAB / 255.0, green: 0x2B / 255.0, blue: 0x28 / 255.0)),
        DistroIcon(id: "openbsd", title: "OpenBSD", color: Color(red: 0xD9 / 255.0, green: 0xA8 / 255.0, blue: 0x0A / 255.0)),
        DistroIcon(id: "netbsd", title: "NetBSD", color: Color(red: 0xFF / 255.0, green: 0x66 / 255.0, blue: 0x00 / 255.0)),
        DistroIcon(id: "osx", title: "macOS", color: Color(red: 0x6E / 255.0, green: 0x6E / 255.0, blue: 0x73 / 255.0)),
        DistroIcon(id: "android", title: "Android", color: Color(red: 0x25 / 255.0, green: 0xA4 / 255.0, blue: 0x67 / 255.0)),
        DistroIcon(id: "routeros", title: "MikroTik RouterOS", color: Color(red: 0x4B / 255.0, green: 0x5A / 255.0, blue: 0x6B / 255.0)),
        DistroIcon(id: "cisco", title: "Cisco IOS", color: Color(red: 0x1B / 255.0, green: 0xA0 / 255.0, blue: 0xD7 / 255.0)),
        DistroIcon(id: "windows", title: "Windows", color: Color(red: 0x00 / 255.0, green: 0x78 / 255.0, blue: 0xD4 / 255.0)),
        DistroIcon(id: "amazon", title: "Amazon Linux", color: Color(red: 0xE8 / 255.0, green: 0x89 / 255.0, blue: 0x0C / 255.0)),
        DistroIcon(id: "mageia", title: "Mageia", color: Color(red: 0x23 / 255.0, green: 0x97 / 255.0, blue: 0xD4 / 255.0)),
    ]

    private static let byId: [String: DistroIcon] = Dictionary(uniqueKeysWithValues: all.map { ($0.id, $0) })

    private static let aliases: [String: String] = [
        "almalinux": "alma",
        "amzn": "amazon",
        "darwin": "osx",
        "linuxmint": "mint",
        "mac": "osx",
        "macos": "osx",
        "opensuse": "suse",
        "raspberry": "raspbian",
        "raspberrypi": "raspbian",
        "rhel": "redhat",
        "rockylinux": "rocky",
        "sles": "suse",
        "win": "windows",
    ]

    /// Icon for a stored `osName`; tolerates legacy free-form values ("Ubuntu 22.04").
    static func forOs(_ osName: String?) -> DistroIcon? {
        let key = (osName ?? "").trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if key.isEmpty { return nil }
        if let icon = byId[aliases[key] ?? key] { return icon }
        if let icon = all.first(where: { $0.id != "linux" && key.contains($0.id) }) { return icon }
        return key.contains("linux") ? byId["linux"] : nil
    }
}
